name: Basic validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - macos-runner-test
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  call-basic-validation:
    name: Basic validation
    uses: priyagupta108/reusable-workflows/.github/workflows/basic-validation.yml@main
    with:
      node-version: '20.x'
